#PROD environment

app:
  message: This is the property file for the ${spring.application.name} specific to PROD Environment

spring:
    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 0911Af
    #url: <POSTGRESS_URL>
    #username: <USERNAME>
    #password: <PASSWORD>

