name: basearch
description: Flutter Sample Architecture Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.1.3


  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  smooth_page_indicator: ^1.0.0+2
  mask_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/i18n/ 
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
    - family: Questrial
      fonts:
        - asset: lib/assets/fonts/Questrial-Regular.ttf
          weight: 400
      #  - asset: lib/assets/fonts/Questrial-Bold.ttf
      #    weight: 400
      #  - asset: lib/assets/fonts/Questrial-LightItalic.ttf
      #    weight: 500
      #    style: italic
      #  - asset: lib/assets/fonts/Questrial-Medium.ttf
      #    weight: 700
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Shaka-Pow
      fonts:
        - asset: lib/assets/fonts/Shaka-Pow.ttf
          weight: 400
    
