#PROD environment

app:
  message: This is the property file for the ${spring.application.name} specific to PROD Environment

spring:
    driver-class-name: org.postgresql.Driver
    url: <POSTGRESS_URL>
    username: <USERNAME>
    password: <PASSWORD>

